### ISSUE TITLE
Download the dataset

### ISSUE THREAD

**Issue by jk3472** [ml-jku/sars-cov-inhibitors-chemai#3]
Hello.
I want to use the dataset used in the paper, but I think the URL link for dataset is wrong.
Could you please check it?
Thank you so much!

**Comment by gfrogat** [comment]
Hi,

Can you please elaborate why you think that the URL is wrong?

The dataset that was used in the paper is linked in the section [Training data set for machine learning or other methods](https://github.com/ml-jku/sars-cov-inhibitors-chemai#training-data-set-for-machine-learning-or-other-methods). Clicking the link will download a ZIP Archive `sars_cov_dataset.zip` which contains the dataset in CSV format as well as the `raw_data` of the assays that were used for compiling the dataset.

```
# content of sars_cov_dataset.zip
├── raw_data
│  ├── AID_1706_datatable_all.csv
│  ├── AID_1879_datatable_all.csv
│  ├── AID_485353_datatable_all.csv
│  ├── AID_652038_datatable_all.csv
│  ├── CID_Smiles_1706.txt.gz
│  ├── CID_Smiles_1879.txt.gz
│  ├── CID_Smiles_485353.txt.gz
│  └── CID_Smiles_652038.txt.gz
├── README.md
└── SARS-Cov.csv
```

I just tried to download it and everything worked fine. If you still encounter any problems please let me know.

Hope this helps.

**Comment by gfrogat** [comment]
Hi,

I assume your problem is solved, so I am closing this issue. Feel free to re-open it if you still have questions.
